AllCops:
  #除外ディレクトリ
  Exclude:
  - bin/*
  - node_modules/**/*
  - config/**/*
  - db/seeds.rb
  - db/migrate/*
  - db/schema.rb
  - vendor/**/*

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# Methodの最大ライン数を100行に増やす
Metrics/MethodLength:
  Max: 100

# 循環的複雑度の制限を無くす
Metrics/CyclomaticComplexity:
  Enabled: false

# ABCSizeのチェックを無くす
Metrics/AbcSize:
  Enabled: false
