AllCops:
  #除外ディレクトリ
  Exclude:
  - bin/*
  - node_modules/**/*
  - config/**/*
  - db/seeds.rb
  - db/migrate/*
  - db/schema.rb
  - vendor/**/*

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false