version: '3.7'

x-rails-base: &rails-base
  build:
    context: .
    dockerfile: Dockerfile
  working_dir: /app
  volumes:
    - bundle:/usr/local/bundle
    - ./:/app
  tmpfs: /app/tmp

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  app:
    <<: *rails-base
    tty: true
    stdin_open: true
    command: /bin/sh -c 'rm -f tmp/pids/server.pid && ./bin/rails server -p 3000 -b 0.0.0.0'
    ports:
      - '13000:3000'
    environment:
      MYSQL_HOST: 'db'
    depends_on:
      - db

  webpack:
    <<: *rails-base
    command: ['bin/webpack-dev-server']
    ports:
      - '13035:3035'
    depends_on:
      - app

volumes:
  db:
  bundle:
