name: lint
on: [push]

jobs:
  lint-ruby:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.4
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('Gemfile.lock') }}
      - uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Install yarn and node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
          npm install -g yarn
          yarn install
      - name: Install ruby dependencies
        run: |
          gem install bundler
          bundle --path vendor/bundle
          bundle update --bundler
          bundle install --quiet --jobs 4 --retry 3
      - name: Run linters
        run: |
          bundle exec rubocop
